ong/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('area-restrita/', login_required(views.area_restrita), name='area-restrita'),

    path('login/', views.my_login_view, name='login'),  # Página de login personalizada

    #path('area-restrita/criancas/', views.criancas, name='criancas'),

    #path('area-restrita/cadastro/', login_required(views.cadastro), name='cadastro'),

    path('home', views.home_view, name='home'),
    path('sobrenos', views.about_us, name='sobrenos'),
    path('projetos', views.projetos, name='projetos'),
    path('cadastro-crianca/', views.form_crianca, name='cadastro_crianca'),

    path('criancas/', views.lista_criancas, name='criancas'),

    path('deletar-crianca/<int:id>/', views.deletar_crianca, name='deletar_crianca'),
    path('crianca/<str:cpf>/editar/', views.editar_crianca, name='editar_crianca'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

spartaRIO/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('area-restrita/', include('ong.urls')),
    path('', include('ong.urls')),
]

ong/models.py
from django.db import models

# Create your models here.
class Crianca(models.Model):
    nome = models.CharField(max_length=100)
    nasc = models.DateField()
    cpf = models.CharField(max_length=14, primary_key=True, unique=True, error_messages={
        'unique': 'Já existe uma crianca cadastrada com este CPF.'})
    rg = models.CharField(max_length=12)
    nomeResp = models.CharField(max_length=100)
    pais = models.CharField(max_length=50)
    escola = models.CharField(max_length=100)
    anoEscolar = models.CharField(max_length=20)
    turno = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.nome} - CPF: {self.cpf}"

ong/forms.py
from django import forms
from .models import Crianca

class CriancaForm(forms.ModelForm):
    class Meta:
        model = Crianca
        fields = ['nome', 'nasc', 'cpf', 'rg', 'nomeResp', 'pais', 'escola', 'anoEscolar', 'turno']
        labels = {'nome': 'Nome', 'cpf': 'CPF', 'rg': 'RG', 'nomeResp': 'Nome Responsável', 'pais': 'Nome Pai ou Mãe', 'escola': 'Escola', 'anoEscolar': 'Ano Escolar', 'turno': 'Turno'}

    nasc = forms.DateField(
        input_formats=['%d/%m/%Y'],  # Permite o formato DD/MM/YYYY
        widget=forms.TextInput(attrs={'type': 'text', 'class': 'date-mask'}),  # Tipo 'text' com a máscara
        label="Data de Nascimento"
    )


def clean_cpf(self):
    cpf = self.cleaned_data.get('cpf')
    # Verifica se o CPF já existe em outra criança, mas não no mesmo objeto
    if Crianca.objects.filter(cpf=cpf).exclude(pk=self.instance.pk).exists():
        raise forms.ValidationError('Já existe uma criança com esse CPF. Tente outro.')
    return cpf

ong/views.py
from audioop import reverse

from django.http import HttpResponseRedirect
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CriancaForm
from .models import Crianca

# Create your views here.
def my_login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        # Autentica o usuário
        user = authenticate(request, username=username, password=password)

        if user is not None:
            # Login bem-sucedido
            login(request, user)
            # Redireciona para a página especificada em 'next', ou 'area_restrita' como padrão
            return redirect(request.GET.get('next', 'area_restrita'))
        else:
            # Erro: credenciais inválidas
            return render(request, 'login.html', {
                'error': 'O nome de usuário ou a senha estão incorretos.'
            })

    # Renderiza a página de login em caso de método GET
    return render(request, 'login.html')


def form_crianca(request):
    if request.method == 'POST':
        form = CriancaForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'CadCri.html', {'form': CriancaForm(), 'sucesso': True})
        else:
            return render(request, 'CadCri.html', {'form': form})
    else:
        form = CriancaForm()

    return render(request, 'CadCri.html', {'form': form})

def lista_criancas(request):
    criancas = Crianca.objects.all()
    nome_filter = request.GET.get('filterName', '')
    nascimento_filter = request.GET.get('filterBirthdate', '')
    idade_filter = request.GET.get('filterAge', '')

    if nome_filter:
        criancas = criancas.filter(nome__icontains=nome_filter)
    if nascimento_filter:
        criancas = criancas.filter(nasc=nascimento_filter)
    if idade_filter:
        criancas = criancas.filter(idade=idade_filter)

    if request.method == 'POST':
        if 'limpar_filtros' in request.POST:
            return redirect('criancas')
        if 'deletar' in request.POST:
            pk = request.POST.get('deletar')
            crianca = get_object_or_404(Crianca, pk=pk)
            crianca.delete()
            return redirect('criancas')
        if 'editar' in request.POST:
            pk = request.POST.get('editar')
            crianca = get_object_or_404(Crianca, pk=pk)
            form = CriancaForm(request.POST, instance=crianca)
            if form.is_valid():
                form.save()
                return redirect('criancas')

    context = {'criancas': criancas}
    return render(request, 'criancas.html', context)

def editar_crianca(request, cpf):
    crianca = get_object_or_404(Crianca, cpf=cpf)

    if request.method == 'POST':
        form = CriancaForm(request.POST, instance=crianca)
        if form.is_valid():
            form.save()
            return redirect('criancas')
    else:
        form = CriancaForm(instance=crianca)

    return render(request, 'editar_crianca.html', {'form': form})

def deletar_crianca(request, id):
    crianca = get_object_or_404(Crianca, id=id)
    if request.method == 'POST':
        crianca.delete()
        return redirect('criancas')
    return render(request, 'confirmar_delecao.html', {'crianca': crianca})

def home_view(request):
    return render(request, 'base.html')

def about_us(request):
    return render(request, 'about-us.html')
def projetos(request):
    return render(request, 'projetos.html')


@login_required
def area_restrita(request):
    return render(request, 'indexGestor.html')
@login_required
def criancas(request):
    return render(request, 'criancas.html')
@login_required
def cadastro(request):
    return render(request, 'CadCri.html')

ong/templates/CadCri.html
{% load static %}
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
 <!-- Fonts Google API ============================================= -->
 <link href="https://fonts.googleapis.com/css?family=Poppins:300i,400,400i,500,600,700,800%7CLora:400,400i,700,700i" rel="stylesheet">
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"/>
 <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

 <!-- Stylesheets ============================================= -->
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
 <link href="{% static 'css/styles.css' %}" rel="stylesheet">
 <link href="{% static 'icons.css' %}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<title>Área Restrita</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand ms-5" href="#">
            <img src="{% static 'images/DOElogo.png' %}" width="300" height="90" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
            <ul class="navbar-nav d-flex flex-row">
              <li class="nav-item active">
                <a class="nav-link fs-3 me-5" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link fs-3 me-5" href="../criancas">Crianças</a>
          </li>
            <li class="nav-item active">
              <a class="nav-link fs-3 me-5" href="#" onclick="document.getElementById('logout-form').submit();">Sair</a>

                     <!-- Formulário de logout escondido -->
                     <form id="logout-form" action="{% url 'logout' %}" method="POST" style="display: none;">
                                  {% csrf_token %}
                     </form>
          </li>
            </ul>
        </div>
    </div>
</nav>
  <!--TABELA-->
  <div class="login-page">
    <div class="formCad">
      <form method="POST">
          <h1>Cadastro Criança</h1>
    {% csrf_token %}

    {{ form.as_p }} <!-- Para renderizar os campos do formulário -->


    <button class="btn btn-primary" type="submit">Enviar</button>
</form>

{% if sucesso %}
    <p>Dados enviados com sucesso!</p>
{% endif %}

{% if form.errors %}
    <div class="alert alert-danger">
        {% for field in form %}
            {% for error in field.errors %}
                <p>{{ error }}</p>
            {% endfor %}
        {% endfor %}
    </div>
{% endif %}
    </div>
  </div>

  <script>
        // Aplica a máscara no campo de CPF assim que a página carrega
        $(document).ready(function(){
            $('#id_cpf').mask('000.000.000-00');  // Mascarando o campo CPF
        });
        $(document).ready(function(){
        // Aplica a máscara de data (dd/mm/aaaa)
        $('#id_nasc').mask('00/00/0000');  // Máscara de Data de Nascimento
    });
         $(document).ready(function(){
        // Aplica a máscara de RG (XX.XXX.XXX-X)
        $('#id_rg').mask('00.000.000-0');  // Máscara de RG
    });
         </script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
</body>
</html>

ong/templates/criancas.html
{% load static %}
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
 <!-- Fonts Google API ============================================= -->
 <link href="https://fonts.googleapis.com/css?family=Poppins:300i,400,400i,500,600,700,800%7CLora:400,400i,700,700i" rel="stylesheet">
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"/>
 <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

 <!-- Stylesheets ============================================= -->
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
 <link rel="stylesheet" href="{% static 'css/styles.css' %}">
 <link href="" rel="stylesheet">
<title>Área Restrita</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand ms-5" href="#">
                <img src="../../static/images/DOElogo.png" width="300" height="90" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                <ul class="navbar-nav d-flex flex-row">
                    <li class="nav-item active">
                        <a class="nav-link fs-3 me-5" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                      <a class="nav-link fs-3 me-5" href="{% url 'cadastro_crianca' %}">Cadastro</a>
                  </li>
                    <li class="nav-item active">
                      <a class="nav-link fs-3 me-5" href="#" onclick="document.getElementById('logout-form').submit();">Sair</a>

                     <!-- Formulário de logout escondido -->
                     <form id="logout-form" action="{% url 'logout' %}" method="POST" style="display: none;">
                                  {% csrf_token %}
                     </form>
                  </li>
                </ul>
            </div>
        </div>
    </nav>
<div class="containerTab">
    <form method="GET">
    {% csrf_token %}
    <div class="filtros">
        <h2>Crianças Cadastradas:</h2>
        <label for="filterName">Filtrar por Nome:</label>
        <input type="text" id="filterName" name="filterName" value="{{ filterName }}" placeholder="Digite o nome...">

        <label for="filterBirthdate">Filtrar por Data de Nascimento:</label>
        <input type="date" id="filterBirthdate" name="filterBirthdate" value="{{ filterBirthdate }}">

        <label for="filterAge">Filtrar por Idade:</label>
        <input type="number" id="filterAge" name="filterAge" value="{{ filterAge }}" placeholder="Digite a idade">

        <!-- Botão para Filtrar -->
        <button class="btn btn-primary" type="submit" id="filterBtn">Filtrar</button>
         <button class="btn btn-primary" type="submit" name="limpar_filtros">Limpar Filtros</button>
    </div>
</form>
    <table id="dataTable">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Data de Nascimento</th>
            <th>CPF</th>
            <th>RG</th>
            <th>Responsável</th>
            <th>Pai/Mãe</th>
            <th>Escola</th>
            <th>Ano</th>
            <th>Turno</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        {% for crianca in criancas %}
        <tr>
            <td>{{ crianca.nome }}</td>
            <td>{{ crianca.nasc }}</td>
            <td>{{ crianca.cpf }}</td>
            <td>{{ crianca.rg }}</td>
            <td>{{ crianca.nomeResp }}</td>
            <td>{{ crianca.pais }}</td>
            <td>{{ crianca.escola }}</td>
            <td>{{ crianca.anoEscolar }}</td>
            <td>{{ crianca.turno }}</td>
            <td>
                <!-- Formulário de exclusão -->
                <form method="POST" style="display:inline;">
                    {% csrf_token %}
                    <input type="hidden" name="deletar" value="{{ crianca.cpf }}">
                    <button class="btn btn-danger" type="submit" onclick="return confirm('Tem certeza que deseja excluir essa criança?')">Excluir</button>
                </form>
                <!-- Botão de editar -->
               <a class="btn btn-primary" href="{% url 'editar_crianca' cpf=crianca.cpf %}">Editar</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="10">Nenhuma criança cadastrada.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
    </div>
</div>

</body>
</html>

ong/templates/editar_crianca.html
{% load static %}
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
 <!-- Fonts Google API ============================================= -->
 <link href="https://fonts.googleapis.com/css?family=Poppins:300i,400,400i,500,600,700,800%7CLora:400,400i,700,700i" rel="stylesheet">
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"/>
 <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

 <!-- Stylesheets ============================================= -->
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
 <link rel="stylesheet" href="{% static 'css/styles.css' %}">
 <link href="src/assets/icons.css" rel="stylesheet">
     <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<title>Área Restrita</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand ms-5" href="#">
                <img src="{% static 'images/DOElogo.png' %}" width="300" height="90" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                <ul class="navbar-nav d-flex flex-row">
                    <li class="nav-item active">
                        <a class="nav-link fs-3 me-5" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                      <a class="nav-link fs-3 me-5" href="">Cadastro</a>
                  </li>
                    <li class="nav-item active">
                      <a class="nav-link fs-3 me-5" href="#" onclick="document.getElementById('logout-form').submit();">Sair</a>

                     <!-- Formulário de logout escondido -->
                     <form id="logout-form" action="{% url 'logout' %}" method="POST" style="display: none;">
                                  {% csrf_token %}
                     </form>
                  </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="login-page">
        <div class="formCad">
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <script>
        // Aplica a máscara no campo de CPF assim que a página carrega
        $(document).ready(function(){
            $('#id_cpf').mask('000.000.000-00');  // Mascarando o campo CPF
        });
        $(document).ready(function(){
        // Aplica a máscara de data (dd/mm/aaaa)
        $('#id_nasc').mask('00/00/0000');  // Máscara de Data de Nascimento
    });
         $(document).ready(function(){
        // Aplica a máscara de RG (XX.XXX.XXX-X)
        $('#id_rg').mask('00.000.000-0');  // Máscara de RG
    });
         </script>
    <button class="btn btn-success" type="submit">Salvar</button>
</form>
</form>
        </div>
    </div>
 <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
</body>
</html>

ong/templates/indexGestor.html
{% load static %}
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
 <!-- Fonts Google API ============================================= -->
 <link href="https://fonts.googleapis.com/css?family=Poppins:300i,400,400i,500,600,700,800%7CLora:400,400i,700,700i" rel="stylesheet">
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"/>
 <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

 <!-- Stylesheets ============================================= -->
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
 <link href="../static/css/styles.css" rel="stylesheet">
 <link href="{% static 'icons.css' %}" rel="stylesheet">
<title>Área Restrita</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand ms-5" href="#">
            <img src="../static/images/DOElogo.png" width="300" height="90" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
            <ul class="navbar-nav d-flex flex-row">
                <li class="nav-item active">
                    <a class="nav-link fs-3 me-5" href="home">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link fs-3 me-5" href="criancas">Crianças</a>
              </li>
                <li class="nav-item active">
                 <a class="nav-link fs-3 me-5" href="#" onclick="document.getElementById('logout-form').submit();">Sair</a>

                     <!-- Formulário de logout escondido -->
                     <form id="logout-form" action="{% url 'logout' %}" method="POST" style="display: none;">
                                  {% csrf_token %}
                     </form>
              </li>
             
            </ul>
        </div>
    </div>
</nav>
    <!--LOGIN-->

    <div class="login-page">
        <div class="form">
          <form class="login-form">
            <h1>Bem-vindo à página protegida!</h1>
            <p>Esta é uma área restrita, acessível apenas após o login.</p>
          </form>
        </div>
      </div>

    <script src="../static/js/script.js"></script>
</body>
</html>

ong/templates/login.html
{% load static %}
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Fonts Google API ============================================= -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300i,400,400i,500,600,700,800%7CLora:400,400i,700,700i" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"/>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <!-- Stylesheets ============================================= -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="{% static 'icons.css' %}" rel="stylesheet">

<title>Área Restrita</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand ms-5" href="#">
            <img src="../../static/images/DOElogo.png" width="300" height="90" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end me-5" id="navbarNavDropdown">
            <ul class="navbar-nav d-flex flex-row">
                <li class="nav-item active">
                    <a class="nav-link fs-3" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </div>
</nav>
    <!--LOGIN-->

    <div class="login-page">
        <div class="form">
          <form  method="POST" action="{% url 'login' %}?next=/area-restrita/">
            {% csrf_token %}
            <h2>Bem-Vindo Gestor!</h2>
            <input type="text" name="username" placeholder="Nome" required/>
            <input type="password" name="password" placeholder="Senha" required/>
            <button type="submit">login</button>
          </form>
          {% if form.non_field_errors %}
                <div class="alert alert-danger mt-2">
                    <p><strong>Erro:</strong> O nome de usuário ou a senha estão incorretos. Tente novamente.</p>
                </div>
            {% endif %}
        </div>
      </div>

    <script src="../../static/js/script.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>